#file: noinspection SpringBootApplicationYaml
# 配置框架(使用 java -jar app.jar --spring.profiles.active=develop | release | production 来启动项目, 其中 release 有时间就拿来测试, 而 production 存储在 Github 上, 每次修改 Github 配置就需要刷新(这个有时间可以优化为无需重启))
spring:
  ## 配置名称
  application:
    name: work-date-alive
  ## 配置智能
  ai:
    dashscope:
      api-key: ${ALY_AI_API_KEY}
    chat:
      options:
        model: qwen-plus
    mcp:
      client:
        sse:
          connections:
            work-mcp-server:
              url: http://127.0.0.1:8127

# 配置服务
server:
  ## 配置地址
  address: 127.0.0.1
  ## 配置端口
  port: 8000

# 配置日志
logging:
  level:
    # root: DEBUG # 如果需要仔细调试可以打开这个选项
    cn.com.edtechhub.workdatealive: DEBUG # 控制本项目包内的日志输出等级 TRACE | DEBUG | INFO | WARN | ERROR | FATAL
    org.springframework.ai: DEBUG

# 配置文档
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaiagent.controller
knife4j: # knife4j 的增强配置(不需要增强可以不配)
  basic:
    enable: false
    username: knife4j
    password: Qwe54188_
  enable: true
  setting:
    language: zh_cn

# 配置搜索
search-api:
  api-key: ${WDA_SEARCH_API_KEY}